---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-client

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-client
  namespace: mysql-client

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-client
  namespace: mysql-client

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-client
  namespace: mysql-client
roleRef:
  kind: Role
  name: mysql-client
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: mysql-client

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: mysql-client
  labels:
    app: mysql-client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"    
spec:
  serviceAccountName: mysql-client
  securityContext:
    runAsNonRoot: true
    supplementalGroups: [ 10001] 
    fsGroup: 10001  
  containers:
    - name: mysql-client
      image: andreswebs/mysql-client
      imagePullPolicy: Always
      securityContext:
        runAsUser: 1000      
      stdin: true
      tty: true
      command: ["/bin/sh"]
